### ISSUE TITLE
LCSC Part import fails

### ISSUE THREAD

**Issue by TimGoll** [30350n/inventree_part_import#9]
I had the same issue as #4 and tried to run the master. I might have done something wrong when creating the package, as I never did that before. Nevertheless, when I try to run the master I get this error:

```
$ inventree-part-import C1525 --verbose

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\tigo\scoop\apps\python\current\Scripts\inventree-part-import.exe\__main__.py", line 4, in <module>
  File "C:\Users\tigo\scoop\apps\python\current\Lib\site-packages\inventree_part_import\__init__.py", line 1, in <module>
    from .config import setup_inventree_api
  File "C:\Users\tigo\scoop\apps\python\current\Lib\site-packages\inventree_part_import\config\__init__.py", line 23, in <module>
    from ..error_helper import *
ModuleNotFoundError: No module named 'inventree_part_import.error_helper'
```

**Comment by TimGoll** [comment]
Found my issue, forgot to update the submodules. For anyone having the same problem in the future, the following command does the trick:

`git submodule update --init --recursive`

**Comment by 30350n** [comment]
You can also just directly install the current version from master via `pipx install git+https://github.com/30350n/inventree_part_import.git`
